# ./docker-compose.yml

version: '3'

services:
  graphql:
    build:
      context: .
    #  dockerfile: Dockerfile.dev
    container_name: pjx-graphql-apollo-dev
    command: npm run dev
    volumes:
      - .:/usr/api
    ports:
      - 4000:4000
